version: "3"

tasks:
  run:
    desc: アプリケーションを実行します
    cmds:
      - docker compose run --remove-orphans {{if .BUILD}}--build{{end}} app {{.CLI_ARGS}}
    vars:
      BUILD: '{{.BUILD | default "false"}}'
